const KEY='event-planner-pro-v12-clean';
let state=load(),pin='',user=null,chosen=[],editing=null,currentCat='TW',orderMode='active',selectedAdmin={material:null};
const $=id=>document.getElementById(id);
const euro=n=>(Number(n)||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
const rid=()=>Math.random().toString(36).slice(2,10);
const today=()=>new Date().toISOString().slice(0,10);
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||clone(INITIAL_STATE)}catch(e){return clone(INITIAL_STATE)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(t){$('toast').textContent=t;$('toast').className='show';setTimeout(()=>$('toast').className='',2200)}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function parsePrice(v){let s=String(v??'').replace(',','.').match(/-?\d+(\.\d+)?/);return s?Number(s[0]):0}
function niceDate(d){if(!d)return'';return new Date(d+'T00:00:00').toLocaleDateString('nl-NL',{day:'2-digit',month:'2-digit',year:'numeric'})}
function addDays(input,days){let el=$(input),d=new Date((el.value||today())+'T00:00:00');d.setDate(d.getDate()+days);el.value=d.toISOString().slice(0,10)}
function statusClass(s){s=String(s||'free').toLowerCase();if(s==='reserved'||s==='gereserveerd')return'reserved';if(s==='defect')return'defect';if(s==='inactive'||s==='niet actief')return'inactive';return'free'}
function statusText(s){return{free:'Vrij',reserved:'Gereserveerd',defect:'Defect',inactive:'Niet actief'}[statusClass(s)]}
function catColor(cat){return{TW:'#1683d8',TO:'#f97316',KW:'#22c55e',KA:'#a855f7',SL:'#eab308',EXTRA:'#334155'}[String(cat||'EXTRA').toUpperCase()]||'#334155'}
function ensure(){state.users??=clone(INITIAL_STATE.users||[]);state.materials??=clone(INITIAL_STATE.materials||[]);state.orders??=clone(INITIAL_STATE.orders||[]);state.customers??=[];state.locations??=[];state.alerts??=[];state.adminPin??='1111';state.docs??={logo:'',text:''}}
function init(){ensure();bindLogin();bindNav();bindOrder();bindAdmin();bindLayout();newOrder();renderAll()}
function bindLogin(){document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{pin=(pin+b.dataset.pin).slice(0,4);$('pinView').textContent=pin.padEnd(4,'-').split('').join(' ')});$('pinClear').onclick=()=>{pin='';$('pinView').textContent='- - - -'};$('pinOk').onclick=()=>{let u=state.users.find(x=>x.pin===pin);if(!u){toast('Verkeerde PIN');return}user=u;$('login').classList.add('hidden');$('app').classList.remove('hidden');renderAll()};$('logout').onclick=()=>location.reload()}
function bindNav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('.worktab').forEach(b=>b.onclick=()=>showWorkTab(b.dataset.tab));document.querySelectorAll('.adminTab').forEach(b=>b.onclick=()=>showAdminTab(b.dataset.admin))}
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));renderAll()}
function showWorkTab(idv){document.querySelectorAll('.workpanel').forEach(x=>x.classList.add('hidden'));$(idv).classList.remove('hidden');document.querySelectorAll('.worktab').forEach(x=>x.classList.toggle('active',x.dataset.tab===idv));if(idv==='materialPanel'){renderCats();renderMaterials()}}
function showAdminTab(idv){document.querySelectorAll('.adminPane').forEach(x=>x.classList.add('hidden'));$(idv).classList.remove('hidden');document.querySelectorAll('.adminTab').forEach(x=>x.classList.toggle('active',x.dataset.admin===idv));renderAdmin()}
function bindLayout(){$('themeSelect').onchange=e=>setTheme(e.target.value);$('layoutSelect').onchange=e=>setLayout(e.target.value)}
function setTheme(t){document.body.className=document.body.className.replace(/\btheme-\w+/g,'').trim();document.body.classList.add('theme-'+t);localStorage.setItem('bns-theme',t)}
function setLayout(l){document.body.className=document.body.className.replace(/\blayout-\w+/g,'').trim();document.body.classList.add('layout-'+l);localStorage.setItem('bns-layout',l)}
function restoreLayout(){setTheme(localStorage.getItem('bns-theme')||'blue');setLayout(localStorage.getItem('bns-layout')||'normal')}
function bindOrder(){['startMinus','endMinus'].forEach(idv=>$(idv).onclick=()=>addDays(idv.startsWith('start')?'dateStart':'dateEnd',-1));['startPlus','endPlus'].forEach(idv=>$(idv).onclick=()=>addDays(idv.startsWith('start')?'dateStart':'dateEnd',1));$('materialSearch').oninput=renderMaterials;$('saveOrder').onclick=saveOrder;$('makeOverviewBtn').onclick=makeOverview;$('makeOverviewBottomBtn').onclick=makeOverview;$('printConfirm').onclick=()=>window.print();$('backToEditBtn').onclick=()=>$('confirmationBox').classList.add('hidden');$('saveFromOverviewBtn').onclick=saveOrder;$('printOverviewBtn').onclick=()=>window.print();$('mailOverviewBtn').onclick=()=>safeMail($('confirmationText').value,'Opdrachtbevestiging');$('orderDeposit').oninput=renderChosen}
function safeMail(text,subject){location.href='mailto:?subject='+encodeURIComponent(subject||'Opdrachtbevestiging')+'&body='+encodeURIComponent(text||'')}
function newOrder(){editing=null;chosen=[];$('orderNumber').value=makeNumber();$('dateStart').value=today();$('dateEnd').value=today();['orderTitle','orderBrand','customerName','customerStreet','customerZip','customerCity','customerPhone','customerEmail','locationName','locationStreet','locationZip','locationCity','locationContact','locationPhone','orderVehicle','orderExtra'].forEach(k=>$(k).value='');$('orderStatus').value='Offerte';$('orderDeposit').value=0}
function makeNumber(){let y=new Date().getFullYear();let nums=state.orders.map(o=>String(o.number||'').match(new RegExp('^'+y+'-(\\d+)$'))).filter(Boolean).map(m=>Number(m[1]));return y+'-'+String((nums.length?Math.max(...nums):2500)+1).padStart(4,'0')}
function renderSummary(){if(!$('summary'))return;let mats=chosen.map(x=>x.code).join(', ')||'Nog niets';$('summary').innerHTML=[['Klant',$('customerName').value||'Nog niet gekozen'],['Locatie',$('locationName').value||'Nog niet gekozen'],['Materialen',mats],['Bezorger',$('orderDriver').selectedOptions[0]?.text||'Nog niet gekozen'],['Totaal',$('grandTotal')?.textContent||'€ 0,00']].map(x=>`<div class="summary-card"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}
function cats(){return[...new Set(state.materials.map(m=>String(m.cat||'EXTRA').toUpperCase()))].sort()}
function renderCats(){if(!$('materialCats'))return;let cs=cats();if(!cs.includes(currentCat))currentCat=cs.includes('TW')?'TW':cs[0]||'EXTRA';$('materialCats').innerHTML=cs.map(c=>`<button class="${c===currentCat?'active':''}" style="border-bottom:5px solid ${catColor(c)}" onclick="currentCat='${c}';renderCats();renderMaterials()">${esc(c)}</button>`).join('')}
function renderMaterials(){if(!$('materialList'))return;let q=($('materialSearch').value||'').toLowerCase();let rows=state.materials.filter(m=>String(m.cat||'EXTRA').toUpperCase()===currentCat).filter(m=>!q||(`${m.code} ${m.name} ${m.notes}`).toLowerCase().includes(q));$('materialList').innerHTML=rows.map(m=>{let st=statusClass(m.status),cc=catColor(m.cat);return`<div class="material-row" style="--cat-color:${cc}" onclick="addMat('${m.id}')"><div class="catbar"></div><div class="mat-line"><b>${esc(m.code)}</b> ${esc(m.name)} <small>${esc(m.price||'oude prijs: € 0')}</small></div><span class="pill ${st}"><i></i>${statusText(st)}</span></div>`}).join('')||'<p>Geen materiaal gevonden.</p>'}
function addMat(mid){let m=state.materials.find(x=>x.id===mid);if(!m)return;if(!chosen.some(x=>x.id===mid))chosen.push({...clone(m),qty:1,linePrice:parsePrice(m.price),note:''});renderChosen();renderSummary()}
function renderChosen(){if(!$('chosenMaterials'))return;let dep=parseFloat($('orderDeposit')?.value||0)||0;$('chosenMaterials').innerHTML=chosen.map((m,i)=>`<div class="chosen-row"><b>${esc(m.code)} ${esc(m.name)}</b><input type="number" min="1" value="${m.qty||1}" onchange="chosen[${i}].qty=Number(this.value)||1;renderChosen()"><input type="number" step="0.01" value="${m.linePrice||0}" onchange="chosen[${i}].linePrice=Number(this.value)||0;renderChosen()"><input value="${esc(m.note||'')}" onchange="chosen[${i}].note=this.value"><button class="delete" onclick="chosen.splice(${i},1);renderChosen();renderSummary()">×</button></div>`).join('');let sub=chosen.reduce((s,m)=>s+(Number(m.qty)||1)*(Number(m.linePrice)||0),0),vat=sub*.21;$('materialsTotal').textContent=euro(sub);$('vatTotal').textContent=euro(vat);$('depositTotal').textContent=euro(dep);$('grandTotal').textContent=euro(sub+vat+dep);renderSummary()}
function collectOrder(){return{id:editing||rid(),number:$('orderNumber').value,status:$('orderStatus').value,title:$('orderTitle').value||'Zonder titel',start:$('dateStart').value,end:$('dateEnd').value,brand:$('orderBrand').value,deposit:Number($('orderDeposit').value)||0,customer:{name:$('customerName').value,street:$('customerStreet').value,zip:$('customerZip').value,city:$('customerCity').value,phone:$('customerPhone').value,email:$('customerEmail').value},location:{name:$('locationName').value,street:$('locationStreet').value,zip:$('locationZip').value,city:$('locationCity').value,contact:$('locationContact').value,phone:$('locationPhone').value,show:$('showLocationOnDocs').checked},materials:clone(chosen),driver:$('orderDriver').value,vehicle:$('orderVehicle').value,extra:$('orderExtra').value}}
function saveOrder(){let o=collectOrder(),i=state.orders.findIndex(x=>x.id===o.id);if(i>=0)state.orders[i]=o;else state.orders.push(o);save();toast('Opdracht opgeslagen');showPage('orders')}
function makeOverview(){let o=collectOrder(),lines=[];lines.push(`Opdrachtbevestiging ${o.number}`);lines.push(`Titel: ${o.title}`);lines.push(`Datum: ${niceDate(o.start)} t/m ${niceDate(o.end)}`);lines.push(`Klant: ${o.customer.name}`);if(o.location.show)lines.push(`Locatie: ${o.location.name} ${o.location.street} ${o.location.city}`);lines.push('');lines.push('Materialen:');o.materials.forEach(m=>lines.push(`- ${m.qty||1}x ${m.code} ${m.name} ${euro(m.linePrice||0)} ${m.note||''}`));lines.push('');lines.push(`Subtotaal: ${$('materialsTotal').textContent}`);lines.push(`BTW: ${$('vatTotal').textContent}`);lines.push(`Borg: ${$('depositTotal').textContent}`);lines.push(`Totaal: ${$('grandTotal').textContent}`);if(o.extra)lines.push('\nExtra:\n'+o.extra);$('confirmationText').value=lines.join('\n');$('confirmationBox').classList.remove('hidden')}
function editOrder(oid){let o=state.orders.find(x=>x.id===oid);if(!o)return;editing=o.id;showPage('newOrder');$('orderNumber').value=o.number||makeNumber();$('orderStatus').value=o.status||'Offerte';$('dateStart').value=o.start||today();$('dateEnd').value=o.end||o.start||today();$('orderTitle').value=o.title||'';$('orderBrand').value=o.brand||'';$('customerName').value=o.customer?.name||'';$('locationName').value=o.location?.name||'';$('orderVehicle').value=o.vehicle||'';$('orderExtra').value=o.extra||'';$('orderDeposit').value=o.deposit||0;chosen=clone(o.materials||[]);showWorkTab('materialPanel');renderChosen()}
function cancelOrder(oid){let o=state.orders.find(x=>x.id===oid);if(o){o.status='Geannuleerd';save()}}
function renderOrders(){if(!$('ordersList'))return;let q=($('ordersSearch')?.value||'').toLowerCase();let list=state.orders.filter(o=>orderMode==='cancelled'?o.status==='Geannuleerd':orderMode==='done'?o.status==='Uitgevoerd':o.status!=='Geannuleerd'&&o.status!=='Uitgevoerd').filter(o=>!q||JSON.stringify(o).toLowerCase().includes(q)).sort((a,b)=>(a.start||'').localeCompare(b.start||''));$('ordersList').innerHTML=list.map(o=>`<div class="order-card"><div class="date-tile">${niceDate(o.start).replaceAll('-','<br>')}</div><div><div class="order-title">${esc(o.number)} - ${esc(o.title)}</div><div>Klant: ${esc(o.customer?.name||'')}</div><div>Locatie: ${esc(o.location?.name||'')}</div><div>Materialen: ${(o.materials||[]).map(m=>`<span class="mat-chip"><i style="background:${catColor(m.cat)}"></i>${esc(m.code)}</span>`).join('')}</div><div><span class="tag">${esc(o.status||'')}</span></div></div><div><button onclick="editOrder('${o.id}')">Wijzigen</button> <button class="delete" onclick="cancelOrder('${o.id}')">Annuleren</button></div></div>`).join('')||'<p>Geen opdrachten gevonden.</p>'}
function renderDashboard(){if(!$('statOrders'))return;$('statOrders').textContent=state.orders.length;$('statMaterials').textContent=state.materials.length;$('statAlerts').textContent=(state.alerts||[]).filter(a=>!a.resolved).length;$('dashOrders').innerHTML=state.orders.slice().sort((a,b)=>(a.start||'').localeCompare(b.start||'')).filter(o=>o.status!=='Geannuleerd').slice(0,8).map(o=>`<div class="order-card"><div class="date-tile">${niceDate(o.start).slice(0,5)}</div><div><b>${esc(o.number)} ${esc(o.title)}</b><br>${esc(o.customer?.name||'')}</div><button onclick="editOrder('${o.id}')">Open</button></div>`).join('')}
function renderDrivers(){if(!$('driverList'))return;$('driverList').innerHTML=(state.alerts||[]).filter(a=>!a.resolved).map(a=>`<div class="order-card"><div class="date-tile">🚨</div><div><b>${esc(a.type||'Melding')}</b><br>${esc(a.text||'')}</div><button onclick="resolveAlert('${a.id}')">Opgelost</button></div>`).join('')||'<p>Geen open meldingen.</p>'}
function resolveAlert(aid){let a=state.alerts.find(x=>x.id===aid);if(a){a.resolved=true;save()}}
function bindAdmin(){$('unlockAdmin').onclick=()=>{if($('adminPin').value===(state.adminPin||'1111')){$('adminArea').classList.remove('hidden');renderAdmin()}else toast('Verkeerde PIN')};$('adminSaveMat').onclick=saveAdminMat;$('adminDeleteMat').onclick=deleteAdminMat;$('adminNewMat').onclick=()=>fillMat(null);$('adminMatSearch').oninput=renderAdminMaterials;$('adminSaveUser').onclick=saveUser;$('backupBtn').onclick=backup;$('restoreDemoBtn').onclick=()=>{if(confirm('Reset naar begin-data?')){localStorage.removeItem(KEY);state=clone(INITIAL_STATE);save()}};$('saveDocs').onclick=()=>{state.docs.text=$('docText').value;save();toast('Layout opgeslagen')}}
function renderAdmin(){renderAdminMaterials();renderUsers();if($('docText'))$('docText').value=state.docs?.text||''}
function renderAdminMaterials(){if(!$('adminMatList'))return;let q=($('adminMatSearch').value||'').toLowerCase();$('adminMatList').innerHTML=state.materials.filter(m=>!q||JSON.stringify(m).toLowerCase().includes(q)).slice(0,250).map(m=>`<div class="admin-row"><span><b>${esc(m.code)}</b> ${esc(m.name)} (${esc(m.cat)}) <span class="pill ${statusClass(m.status)}"><i></i>${statusText(m.status)}</span></span><button onclick="fillMat('${m.id}')">Wijzig</button></div>`).join('')}
function fillMat(mid){let m=state.materials.find(x=>x.id===mid)||{id:null,cat:'TW',code:'',name:'',price:'oude prijs: € 0',status:'free'};selectedAdmin.material=m.id;$('adminSelectedMat').textContent=m.id?'Gekozen: '+m.code:'Nieuw materiaal';$('adminMatCat').value=m.cat;$('adminMatCode').value=m.code;$('adminMatName').value=m.name;$('adminMatPrice').value=m.price;$('adminMatStatus').value=statusClass(m.status)}
function saveAdminMat(){let m={id:selectedAdmin.material||rid(),cat:$('adminMatCat').value.toUpperCase()||'EXTRA',code:$('adminMatCode').value,name:$('adminMatName').value,price:$('adminMatPrice').value,status:$('adminMatStatus').value,notes:''};let i=state.materials.findIndex(x=>x.id===m.id);if(i>=0)state.materials[i]=m;else state.materials.push(m);selectedAdmin.material=m.id;save();renderAdminMaterials();renderCats();renderMaterials()}
function deleteAdminMat(){if(!selectedAdmin.material)return;state.materials=state.materials.filter(x=>x.id!==selectedAdmin.material);selectedAdmin.material=null;save()}
function renderUsers(){if($('orderDriver'))$('orderDriver').innerHTML='<option value="">Geen</option>'+state.users.filter(u=>u.role==='Bezorger').map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');if($('adminUserList'))$('adminUserList').innerHTML=state.users.map(u=>`<div class="admin-row"><span>${esc(u.name)} - ${esc(u.role)}</span></div>`).join('')}
function saveUser(){state.users.push({id:rid(),name:$('adminUserName').value,pin:$('adminUserPin').value,role:$('adminUserRole').value,rights:{}});save();renderUsers()}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='event-planner-backup.json';a.click()}
function renderAlerts(){let n=(state.alerts||[]).filter(a=>!a.resolved).length;$('alertsBtn').textContent='Systeemmeldingen ('+n+')';$('alertsBtn').classList.toggle('alert-blink',n>0)}
function renderAll(){renderDashboard();renderSummary();renderCats();renderMaterials();renderChosen();renderOrders();renderDrivers();renderAdmin();renderUsers();renderAlerts()}
window.addMat=addMat;window.editOrder=editOrder;window.cancelOrder=cancelOrder;window.fillMat=fillMat;window.resolveAlert=resolveAlert;
document.addEventListener('DOMContentLoaded',()=>{restoreLayout();init();$('ordersSearch').oninput=renderOrders;$('activeOrders').onclick=()=>{orderMode='active';renderOrders()};$('doneOrders').onclick=()=>{orderMode='done';renderOrders()};$('cancelledOrders').onclick=()=>{orderMode='cancelled';renderOrders()};});
